package com.hiaashuu.debloatzzz.data

import android.content.Context
import android.os.Build
import android.os.Environment
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import com.google.gson.reflect.TypeToken
import com.hiaashuu.debloatzzz.model.BackupEntry
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.UUID

class BackupManager(private val context: Context) {

    private val gson: Gson = GsonBuilder().setPrettyPrinting().create()

    private val backupDir: File = File(context.getExternalFilesDir(null), "backups").also { it.mkdirs() }

    private val scriptsDir: File = File(
        Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),
        "Debloatzzz"
    ).also { it.mkdirs() }

    data class RawBackupData(
        val id: String,
        val timestamp: Long,
        val deviceModel: String,
        val androidVersion: Int,
        val packages: List<String>,
        val label: String
    )

    fun createBackup(packages: List<String>, label: String = ""): BackupEntry? {
        return try {
            val id = UUID.randomUUID().toString().take(8)
            val timestamp = System.currentTimeMillis()
            val deviceModel = "${Build.MANUFACTURER} ${Build.MODEL}".trim()
            val androidVersion = Build.VERSION.SDK_INT

            val dateStr = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date(timestamp))
            val filename = "DeBloatzzz_Backup_${dateStr}.json"
            val file = File(backupDir, filename)

            val rawData = RawBackupData(
                id = id,
                timestamp = timestamp,
                deviceModel = deviceModel,
                androidVersion = androidVersion,
                packages = packages,
                label = label.ifEmpty { "Backup $dateStr" }
            )

            file.writeText(gson.toJson(rawData))

            BackupEntry(
                id = id,
                timestamp = timestamp,
                deviceModel = deviceModel,
                androidVersion = androidVersion,
                packages = packages,
                filename = filename,
                label = label.ifEmpty { "Backup $dateStr" }
            )
        } catch (e: Exception) {
            null
        }
    }

    fun listBackups(): List<BackupEntry> {
        return try {
            backupDir.listFiles { file -> file.name.endsWith(".json") }
                ?.mapNotNull { file ->
                    try {
                        val json = file.readText()
                        val raw: RawBackupData = gson.fromJson(json, RawBackupData::class.java)
                        BackupEntry(
                            id = raw.id,
                            timestamp = raw.timestamp,
                            deviceModel = raw.deviceModel,
                            androidVersion = raw.androidVersion,
                            packages = raw.packages,
                            filename = file.name,
                            label = raw.label
                        )
                    } catch (e: Exception) {
                        null
                    }
                }
                ?.sortedByDescending { it.timestamp }
                ?: emptyList()
        } catch (e: Exception) {
            emptyList()
        }
    }

    fun deleteBackup(filename: String): Boolean {
        return try {
            File(backupDir, filename).delete()
        } catch (e: Exception) {
            false
        }
    }

    fun getBackupFilePath(filename: String): String {
        return File(backupDir, filename).absolutePath
    }

    fun generateUninstallBatFile(packages: List<String>, filename: String = ""): File? {
        return try {
            val dateStr = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
            val outName = filename.ifEmpty { "DeBloatzzz_Uninstall_${dateStr}.bat" }
            val file = File(scriptsDir, outName)

            val sb = StringBuilder()
            sb.appendLine("@echo off")
            sb.appendLine("title DeBloatzzz - Android Debloat Script")
            sb.appendLine("color 0B")
            sb.appendLine("echo.")
            sb.appendLine("echo  ====================================================")
            sb.appendLine("echo     DeBloatzzz - Uninstall Script for Android")
            sb.appendLine("echo     Generated by DeBloatzzz App")
            sb.appendLine("echo  ====================================================")
            sb.appendLine("echo.")
            sb.appendLine("echo  [INFO] Make sure ADB is installed and on your PATH.")
            sb.appendLine("echo  [INFO] USB Debugging must be enabled on your device.")
            sb.appendLine("echo  [INFO] Run 'adb devices' to confirm device is connected.")
            sb.appendLine("echo.")
            sb.appendLine("echo  [STEP 1] Checking device connection...")
            sb.appendLine("adb devices")
            sb.appendLine("echo.")
            sb.appendLine("echo  [STEP 2] Uninstalling ${packages.size} package(s)...")
            sb.appendLine("echo.")

            packages.forEach { pkg ->
                val info = AppDataSource.getBloatInfo(pkg)
                val name = info?.displayName ?: pkg
                sb.appendLine("echo  -> Removing: $name")
                sb.appendLine("adb shell pm uninstall -k --user 0 $pkg")
                sb.appendLine("echo.")
            }

            sb.appendLine("echo  ====================================================")
            sb.appendLine("echo  [DONE] Debloating complete!")
            sb.appendLine("echo  [INFO] Restart your device for all changes to take effect.")
            sb.appendLine("echo  [INFO] To restore, run the restore script generated by DeBloatzzz.")
            sb.appendLine("echo  ====================================================")
            sb.appendLine("echo.")
            sb.appendLine("pause")

            file.writeText(sb.toString())
            file
        } catch (e: Exception) {
            null
        }
    }

    fun generateRestoreBatFile(packages: List<String>, filename: String = ""): File? {
        return try {
            val dateStr = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
            val outName = filename.ifEmpty { "DeBloatzzz_Restore_${dateStr}.bat" }
            val file = File(scriptsDir, outName)

            val sb = StringBuilder()
            sb.appendLine("@echo off")
            sb.appendLine("title DeBloatzzz - Restore Script")
            sb.appendLine("color 0A")
            sb.appendLine("echo.")
            sb.appendLine("echo  ====================================================")
            sb.appendLine("echo     DeBloatzzz - Restore Script for Android")
            sb.appendLine("echo     Generated by DeBloatzzz App")
            sb.appendLine("echo  ====================================================")
            sb.appendLine("echo.")
            sb.appendLine("echo  [INFO] This script restores ${packages.size} previously removed system app(s).")
            sb.appendLine("echo.")
            sb.appendLine("echo  [STEP 1] Checking device connection...")
            sb.appendLine("adb devices")
            sb.appendLine("echo.")
            sb.appendLine("echo  [STEP 2] Restoring packages...")
            sb.appendLine("echo.")

            packages.forEach { pkg ->
                val info = AppDataSource.getBloatInfo(pkg)
                val name = info?.displayName ?: pkg
                sb.appendLine("echo  -> Restoring: $name")
                sb.appendLine("adb shell cmd package install-existing --user 0 $pkg")
                sb.appendLine("echo.")
            }

            sb.appendLine("echo  ====================================================")
            sb.appendLine("echo  [DONE] Restore complete!")
            sb.appendLine("echo  [INFO] Restart your device if apps are not visible.")
            sb.appendLine("echo  ====================================================")
            sb.appendLine("echo.")
            sb.appendLine("pause")

            file.writeText(sb.toString())
            file
        } catch (e: Exception) {
            null
        }
    }

    fun getScriptsDirectory(): String {
        return scriptsDir.absolutePath
    }

    fun getBackupsDirectory(): String {
        return backupDir.absolutePath
    }
}